# Generated by Django 5.2.2 on 2025-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_usertask_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AddField(
            model_name='taskfeedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
    ]
