# Generated by Django 5.2.2 on 2025-06-12 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_taskfeedback_options_alter_usertask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='templatesection',
            options={},
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='expected_duration',
        ),
        migrations.AddField(
            model_name='templateitem',
            name='expected_duration_new',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='document',
            field=models.FileField(blank=True, upload_to='onboarding_docs/'),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='item_type',
            field=models.CharField(choices=[('GUIDE', 'Learning Guide'), ('DOC', 'Document'), ('TOOL', 'Tool Setup'), ('TASK', 'Practical Task')], max_length=10),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='templatesection',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_templates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingtemplate')),
            ],
            options={
                'unique_together': {('template', 'assignee')},
            },
        ),
    ]
