# Generated by Django 5.2.2 on 2025-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_usertask_kpi_points_alter_usertask_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='was_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpi',
            name='was_late',
            field=models.BooleanField(default=False),
        ),
    ]
