services:
  - type: web
    name: onboardkit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn config.wsgi:application

    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: onboardkit-db
          property: connectionString

    staticPublishPath: staticfiles
